language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - "pip install -U pip"
  - "pip install git+https://github.com/rlaverde/lektor.git@themes#egg=Lektor"
script: "lektor build"
deploy:
  provider: script
  script: "lektor deploy production"
